version: '3'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    networks:
      - backend

  bookapi:
    image: books
    depends_on:
      - mongo
    ports:
      - "5001:5001"
    expose:
      - 5001
    restart: always
    networks:
      - backend
      
networks:
  backend:
    driver: bridge
