name: Books Service CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Record start time
        run: echo "Start Time:$(date -Iminutes)" > log.txt

      - name: Add submitter names to log
        run: echo "Omer Yanay, Yuval Lapid" >> log.txt  

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Build and export
        uses: docker/build-push-action@v3
        with:
          context: ./bookapi
          file: ./bookapi/Dockerfile
          tags: books:latest
          outputs: type=docker,dest=/tmp/image.tar

      - name: Log build success
        run: |
          if [ $? -eq 0 ]; then
            echo "image successfully built" >> log.txt
          else
            echo "image not able to be built" >> log.txt
            exit 1
          fi     
 
      - name: Upload Docker image and log
        uses: actions/upload-artifact@v3
        with:
          name: books
          path: /tmp/image.tar

      - name: Upload log
        uses: actions/upload-artifact@v3
        with:
          name: log
          path: log.txt

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Docker image and log
        uses: actions/download-artifact@v3

      - name: Load Docker image
        run: docker load --input books/image.tar

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: |
          docker compose -f docker-compose.yml up -d
          if [ $? -eq 0 ]; then
            echo "Container up and running" >> log.txt
          else
            echo "Container failed to run" >> log.txt
            exit 1
          fi

      - name: Check container status
        run: docker ps

      - name: Set up Python
        uses: actions/setup-python@v4
    
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install requests
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run tests
        run: |
          pytest -v ./tests/assn3_tests.py > assn3_test_results.txt
          if [ $? -eq 0 ]; then
            echo "tests succeeded" >> log.txt
          else
            echo "tests failed" >> log.txt
            exit 1
          fi

      - name: Upload test results 
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: pytest-results
          path: |
            assn3_test_results.txt  
            
      - name: Tear down Docker Compose
        run: docker-compose -f docker-compose.yml down

  query:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Download Docker image and log
        uses: actions/download-artifact@v3
        
      - name: Load Docker image
        run: docker load --input books/image.tar

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: docker compose -f docker-compose.yml up -d

      - name: Check container status
        run: docker ps

      - name: Curl POST requests
        run: |
          book1='{"title":"Adventures of Huckleberry Finn", "ISBN":"9780520343641", "genre":"Fiction"}'
          book2='{"title":"The Best of Isaac Asimov", "ISBN":"9780385050784", "genre":"Science Fiction"}'
          book3='{"title":"Fear No Evil", "ISBN":"9780394558783", "genre":"Biography"}'
          book6='{"title":"The Adventures of Tom Sawyer", "ISBN":"9780195810400", "genre":"Fiction"}'
          book7='{"title":"I, Robot", "ISBN":"9780553294385", "genre":"Science Fiction"}'
          book8='{"title":"Second Foundation", "ISBN":"9780553293364", "genre":"Science Fiction"}'
          sleep 10
          curl -L -X POST -m 10 -H "Content-Type: application/json" -d "$book1" http://127.0.0.1:5001/books
          curl -L -X POST -m 10 -H "Content-Type: application/json" -d "$book2" http://127.0.0.1:5001/books
          curl -L -X POST -m 10 -H "Content-Type: application/json" -d "$book3" http://127.0.0.1:5001/books
          curl -L -X POST -m 10 -H "Content-Type: application/json" -d "$book6" http://127.0.0.1:5001/books
          curl -L -X POST -m 10 -H "Content-Type: application/json" -d "$book7" http://127.0.0.1:5001/books
          curl -L -X POST -m 10 -H "Content-Type: application/json" -d "$book8" http://127.0.0.1:5001/books

      - name: Run query script
        run: python scripts/process_queries.py

      - name: Upload query results and log
        uses: actions/upload-artifact@v3
        with:
          name: query-response
          path: |
            response.txt
            log.txt

      - name: Tear down Docker Compose
        run: docker-compose -f docker-compose.yml down
