name: Books Service CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Record start time
        run: echo "Start Time:$(date -Iminutes)" > log.txt

      - name: Build Docker image
        run: |
          docker build -t books-service .
          echo "Image successfully built" >> log.txt

      - name: Save Docker image
        run: docker save books-service | gzip > books-service.tar.gz

      - name: Upload Docker image and log
        uses: actions/upload-artifact@v3
        with:
          name: docker-image
          path: books-service.tar.gz

      - name: Upload log
        uses: actions/upload-artifact@v3
        with:
          name: build-log
          path: log.txt

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Docker image and log
        uses: actions/download-artifact@v3
        with:
          name: docker-image

      - name: Load Docker image
        run: gunzip -c books-service.tar.gz | docker load

      - name: Create network
        run: docker network create my-net

      - name: Start MongoDB container
        run: docker run --name mongodb --network my-net -d mongo

      - name: Start Books Service container
        run: docker run --name books-service --network my-net -p 5001:5001 -d books-service

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
    
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest requests
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run tests
        run: pytest -v ./tests/assn3_tests.py > assn3_test_results.txt

      - name: Upload test results and log
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results-and-log
          path: |
            assn3_test_results.txt
            log.txt

  query:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Docker image and test results
        uses: actions/download-artifact@v3
        with:
          name: test-results-and-log

      - name: Load Docker image
        run: gunzip -c books-service.tar.gz | docker load

      - name: Start MongoDB container
        run: docker run --name mongodb --network my-net -d mongo

      - name: Start Books Service container
        run: docker run --name books-service --network my-net -p 5001:5001 -d books-service

      - name: Run query processor
        run: python scripts/process_queries.py

      - name: Upload query results and log
        uses: actions/upload-artifact@v3
        with:
          name: final-results-and-log
          path: |
            response.txt
            log.txt
