name: Books Service CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Record start time
        run: echo "Start Time:$(date -Iminutes)" > log.txt

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Build and export
        uses: docker/build-push-action@v3
        with:
          context: ./bookapi
          file: ./bookapi/Dockerfile
          tags: books:latest
          outputs: type=docker,dest=/tmp/image.tar

      - name: Upload Docker image and log
        uses: actions/upload-artifact@v3
        with:
          name: books
          path: /tmp/image.tar

      - name: Upload log
        uses: actions/upload-artifact@v3
        with:
          name: build-log
          path: log.txt

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Docker image and log
        uses: actions/download-artifact@v3
        
      - name: Load Docker image
        run: docker load --input books/image.tar

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: docker compose -f docker-compose.yml up -d

      - name: Check container status
        run: docker ps

      - name: Set up Python
        uses: actions/setup-python@v4
    
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install requests
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run tests
        run: pytest -v ./tests/assn3_tests.py > assn3_test_results.txt

      - name: Upload test results and log
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results-and-log
          path: |
            assn3_test_results.txt
            log.txt

      - name: Tear down Docker Compose
        run: docker-compose -f docker-compose.yml down

  query:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Download Docker image and log
        uses: actions/download-artifact@v3
        
      - name: Load Docker image
        run: docker load --input books/image.tar

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: docker compose -f docker-compose.yml up -d

      - name: Check container status
        run: docker ps

      - name: Curl POST requests
        run: |
          curl -L -X POST -m 10 -H "Content-Type: application/json" -d '{"title":"Adventures of Huckleberry Finn", "ISBN":"9780520343641", "genre":"Fiction"}' http://127.0.0.1:5001/books
          curl -L -X POST -m 10 -H "Content-Type: application/json" -d '{"title":"The Best of Isaac Asimov", "ISBN":"9780385050784", "genre":"Science Fiction"}' http://127.0.0.1:5001/books
          curl -L -X POST -m 10 -H "Content-Type: application/json" -d '{"title":"Fear No Evil", "ISBN":"9780394558783", "genre":"Biography"}' http://127.0.0.1:5001/books
          curl -L -X POST -m 10 -H "Content-Type: application/json" -d '{"title":"The Adventures of Tom Sawyer", "ISBN":"9780195810400", "genre":"Fiction"}' http://127.0.0.1:5001/books
          curl -L -X POST -m 10 -H "Content-Type: application/json" -d '{"title":"I, Robot", "ISBN":"9780553294385", "genre":"Science Fiction"}' http://127.0.0.1:5001/books
          curl -L -X POST -m 10 -H "Content-Type: application/json" -d '{"title":"Second Foundation", "ISBN":"9780553293364", "genre":"Science Fiction"}' http://127.0.0.1:5001/books

      - name: Run query script
        run: python scripts/process_queries.py

      - name: Upload query results and log
        uses: actions/upload-artifact@v3
        with:
          name: final-results-and-log
          path: |
            response.txt
            log.txt

      - name: Tear down Docker Compose
        run: docker-compose -f docker-compose.yml down
