name: Books Service CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Record start time
        run: echo "Start Time:$(date -Iminutes)" > log.txt

      - name: Build Docker image
        run: |
          docker-compose -f ./docker-compose.yml build
          echo "Images successfully built" >> log.txt

      - name: Save Docker image
        run: docker save bookapi | gzip > bookapi.tar.gz

      - name: Upload Docker image and log
        uses: actions/upload-artifact@v3
        with:
          name: docker-image
          path: bookapi.tar.gz

      - name: Upload log
        uses: actions/upload-artifact@v3
        with:
          name: build-log
          path: log.txt

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Docker image and log
        uses: actions/download-artifact@v3
        with:
          name: docker-image

      - name: Load Docker image
        run: gunzip -c bookapi.tar.gz | docker load

      - name: Set up Docker Compose
        run: docker-compose -f docker-compose.yml up -d

      - name: Check container status
        run: docker-compose -f docker-compose.yml ps

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
    
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest requests
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run tests
        run: pytest -v ./tests/assn3_tests.py > assn3_test_results.txt

      - name: Upload test results and log
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results-and-log
          path: |
            assn3_test_results.txt
            log.txt

      - name: Tear down Docker Compose
        run: docker-compose -f docker-compose.yml down

  query:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Docker image and test results
        uses: actions/download-artifact@v3
        with:
          name: test-results-and-log

      - name: Load Docker image
        run: gunzip -c bookapi.tar.gz | docker load

      - name: Set up Docker Compose
        run: docker-compose -f docker-compose.yml up -d

      - name: Run query processor
        run: python scripts/process_queries.py

      - name: Upload query results and log
        uses: actions/upload-artifact@v3
        with:
          name: final-results-and-log
          path: |
            response.txt
            log.txt

      - name: Tear down Docker Compose
        run: docker-compose -f docker-compose.yml down
